# Generated by Django 4.2.7 on 2023-12-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
