# Generated by Django 4.2.7 on 2023-12-02 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10, message='Phone number must be exactly 10 characters.'), django.core.validators.MaxLengthValidator(10, message='Phone number must be exactly 10 characters.')]),
        ),
    ]
