# Generated by Django 4.2.7 on 2024-01-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_delete_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address2',
            field=models.CharField(max_length=100,null=True, blank=True, default=''),
        ),
    ]
