# Generated by Django 4.2.7 on 2023-12-21 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='street',
        ),
    ]
