# Generated by Django 4.2.7 on 2023-12-08 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_emailverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
