# Generated by Django 4.2.7 on 2023-12-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_address_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_from_checkout',
            field=models.BooleanField(default=False),
        ),
    ]
