# Generated by Django 4.2.7 on 2024-06-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
